#!/usr/bin/bash
./scripts/sudo.sh
./scripts/i3-gaps.sh
./scripts/vscode.sh
./scripts/install.sh
./scripts/chrome.sh
./scripts/remove.sh
./scripts/upgrade.sh
./scripts/configure.sh
./scripts/bash_append.sh
./scripts/picom.sh